name: Theme Manager

on:
  workflow_dispatch:
    inputs:
      theme-url:
        description: "Enter the theme URL"
        required: true

jobs:
  build:
    name: Add Theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r _src/requirements.txt

      - name: Add Theme
        id: add-theme
        run: python _src/theme-manager.py add community ${{ github.events.inputs.theme-url }}

      - name: Publish Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add ${{ steps.add-theme.outputs.THEME_ID }} theme
