name: Site Builder

on:
  push:
    branches:
      - master
    paths:
      - '_src/**'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      theme-url:
        description: 'Enter the theme URL'
        required: true

jobs:
  build:
    name: Site Builder
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: 'Update themes website'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r _src/requirements.txt

      - name: Add Theme
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: python _src/theme-manager.py add community ${{ github.event.inputs.theme-url }}

      - name: Rebuild Site
        run: python _src/site-builder.py

      - name: Publish Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}

      - name: Purge CDN Cache
        run: curl https://purge.jsdelivr.net/gh/t1m0thyj/WDD-website/themes/themes.db.js
