name: Link Checker

on:
  workflow_run:
    workflows: ["Site Builder"]
    types: [completed]

jobs:
  check-links:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress themes/*.html themes/preview/*.html
