name: Link Checker

on:
  workflow_run:
    workflows: ["Site Builder"]
    types: [completed]

jobs:
  check-links:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --accept 403 --no-progress --verbose themes/*.html themes/preview/*.html
