name: Link Check

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Link Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.2.0
        with:
          args: --verbose --no-progress '**/*.html'
